config/routes.rb
Rails.application.routes.draw do
  #get 'main/index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  devise_for :users
  get 'main/index'
   	resources :articles do
   		resources :comments
 	  	
      member do
   			get :add_comment
   			post :create_comment
 	  	end
   	end
   	
  root 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments
	has_attached_file :foto, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :foto, content_type: /\Aimage\/.*\z/

	def self.search(search)
	  where('title LIKE ?', "%#{search}%") | where('text LIKE ?', "%#{search}%")
	end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :text, presence: true,
                    length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except: [:show, :add_comment, :create_comment, :index]
	def index
		@articles = Article.all
	end
	
	def show
     	@article = Article.find(params[:id])
  	end

  	def edit
  		@article = Article.find(params[:id])
	end

  	def create_comment
		@comment = Comment.new(comment_params)
		@article = Article.find(params[:id])
		if @article.comments << @comment
			redirect_to @article
		else
			render 'add_comment'
		end
	end

  	def add_comment
  		@comment = Comment.new()
     	@article = Article.find(params[:id])
  	end

	def new
	end

	def create
		@article = Article.new(article_params)
 		@article.save
		redirect_to @article	
	end

	def update
  		@article = Article.find(params[:id])
 
  		if @article.update(article_params)
    		redirect_to @article
  		else
    		render 'edit'
  		end
	end

	def destroy
  		@article = Article.find(params[:id])
  		@article.destroy
		redirect_to articles_path
	end

	private
 	def article_params
		params.require(:article).permit(:title, :text, :foto)
  	end

	def comment_params
		params.require(:comment).permit(:commenter, :text)
  	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def new
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)
	end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
	if params[:search]
    @articles = Article.search(params[:search])
  else
    @articles = Article.page params[:page]
  end
   end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/add_comment.html.erb
<p>
  <strong>Agrega un comentario:</strong>
</p>
 
<p>
	<%= form_for :comment, url: create_comment_article_path(@article) do |f| %>
	
	<% @comment.errors.each do |attr,msg|  %>
		 <%= attr %> - <%=msg%>
		 <br/>
	<% end %>

	<p>
    	<strong><%= f.label :Tu_nombre %></strong>
   		<br>
    	<%= f.text_field :commenter %>
    </p>
 	<p>
 	  <strong><%= f.label :Texto %><br></strong>
  	  <%= f.text_area :text %>
 	</p>
 
  	<p>
    	<%= f.submit :Guardar %>
  	</p>
	<% end %>

</p>

app/views/articles/edit.html.erb
<strong>Editando articulo</strong>
 
<%= form_for :article, url: article_path(@article), html: { multipart: true }, method: :patch do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :Titulo %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :Texto %><br>
    <%= f.text_area :text, :class => "tinymce", :rows => 10, :cols => 30 %>
    <%= tinymce %>
  </p>
 <%= f.file_field :foto %>
 <br>
  <p>
    <%= f.submit 'Guardar' %>
  </p>
 
<% end %>
 
<%= link_to 'Atras', root_path %>

app/views/articles/index.html.erb
<h1>Listado de articulos</h1>
<%= link_to 'Inicio', root_path %> | <%= link_to 'Template', '/start' %>
<% if user_signed_in? %>
<%= link_to 'Nuevo articulo', new_article_path %> | <%= link_to 'Emails', "/letter_opener" %> | 
<% end %>

<%= form_tag(main_index_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Buscador de articulos" %>
<%= submit_tag "Buscar" %>
<% end %>

<br/>
<br/>
<% if @articles.present? %>
  <table>
    <tr align="center">
      <th>Imagen</th>
      <th>Titulo</th>
      <th>Texto</th>
    </tr>
   
    <% @articles.each do |article| %>
      <tr>
        <td><%= image_tag article.foto.url(:thumb) %> </td>  
        <td> <%= article.title %> </td>
        <td> <%= article.text %> </td>
        <td> <%= link_to 'Mostrar', article_path(article) %>
        <% if user_signed_in? %>
             | <%= link_to 'Edit', edit_article_path(article) %> | 
            <%= link_to 'Eliminar', article_path(article),
                method: :delete,
                data: { confirm: 'Estas seguro de eliminar este articulo?' } %>
        <% end %>
      </td>
      </tr>
    <% end %>
  </table>
  <% else %>
   <p>No hay ningun articulo con "<%= params[:search] %>".</p>
<% end %>

<% if params[:search] == nil %>
  <%= paginate @articles %>
<% end %>

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path, html: { multipart: true } do |f| %>
  <p>
    <strong><%= f.label :titulo %></strong>
    <br>
    <%= f.text_field :title %>
  </p>
 
 
    <strong><%= f.label :texto %><br></strong>

    <%= f.text_area :text, :class => "tinymce", :rows => 10, :cols => 30 %>
    <%= tinymce %>

  
  <%= f.file_field :foto %>
 <br>
  <p>
    <%= f.submit :Guardar %>
  </p>
<% end %>
<%= link_to 'Atras', root_path %>

app/views/articles/show.html.erb


<!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    
  <script type="text/javascript">
		var someimage = document.getElementById('this_one').firstChild.getAttribute('src');
		document.getElementById("myDiv").style.backgroundImage= "url(/system/articles/fotos/000/000/001/original/Linux-wallpapers-22-800x600.jpg?1492646382)";
		    	   	
	</script>


	    <header class="intro-header" id="myDiv">

	        <div class="container">
	            <div class="row">
	                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
	                    <div class="post-heading">
	                        <h1><%= @article.title %></h1><p id="demo"></p>
	                    </div>
	                </div>
	            </div>
	        </div>
	    <div class="image_post" id="this_one" style="visibility: hidden;"><%= image_tag @article.foto.url %></div>	
	
	    </header>
    



    <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <%= @article.text %>
                </div>
            </div>
        </div>
    </article>
	<h3><%= link_to 'Atras', root_path %></h3>
    <hr>

	<h2>Comentarios:</h2>

	<h3><%= render @article.comments %></h3>

	<h3><%= link_to 'Comentar', add_comment_article_path(@article) %></h3>


    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <hr>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2016</p>
                </div>
            </div>
        </div>
    </footer>

app/views/comments/_comment.html.erb


<p>
    <strong>- <%= comment.commenter %>: </strong> <%= comment.text %> 
    <% if user_signed_in? %>
    	<%= link_to 'Eliminar', 
									[comment.article, comment], 
									method: :delete,
									data: { confirm: 'Estas seguro de eliminar este comentario?' } %>
	<% end %>									
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Cool Blog</title>

    <!-- Bootstrap Core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="css/clean-blog.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                  </button>
                  <a class="navbar-brand">
                    <% if user_signed_in? %>
                      <%= current_user.email %>
                      <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
                      <%= link_to "Salir", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                    <% else %>
                      <%= link_to "Registrate", new_user_registration_path, :class => 'navbar-link'  %> |
                      <%= link_to "Ingresa", new_user_session_path, :class => 'navbar-link'  %>
                    <% end %> 
                  </a>           
             
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/">Inicio</a>
                    </li>
                    <% if user_signed_in? %>
                      <li>
                          <a href="/articles/new.html">Nuevo articulo</a>
                      </li>
                      <li>
                          <a href="/letter_opener">Emails</a>
                      </li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/main/index.html.erb
    <header class="intro-header" style="background-image: url('/images/home.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>Cool Blog</h1>
                    <hr class="small">
                    <span class="subheading">A blog maked with Ruby on Rails</span>
                </div>
            </div>
        </div>
    </div>
    <%= form_tag(main_index_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Buscador" %>
      <%= submit_tag "Buscar" %>
    <% end %>
    </header>


<% if @articles.present? %>
 <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              <% @articles.each do |article| %>
                <div class="post-preview">
                    
                    <a href='/articles/<%= article.id %>'>
                        <h2 class="post-title">
                          <%= article.title %>
                        </h2>
                        <h3 class="post-subtitle">
                            <%= article.text %>
                        </h3>
                        
                        <% if user_signed_in? %>
                          <p class="post-meta"> 
                          <%= link_to 'Editar', edit_article_path(article) %> | 
                              <%= link_to 'Eliminar', article_path(article),
                                  method: :delete,
                                  data: { confirm: 'Estas seguro de eliminar este articulo?' } %>
                          <% end %>
                            </p>
                    </a>
                </div>
                <hr>
<% end %>
  <% else %>
   <p>No hay ningun articulo con "<%= params[:search] %>".</p>
<% end %>

<% if params[:search] == nil %>
  <h3 align='center'><%= paginate @articles %></h3>
<% end %>


    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2016</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="js/jqBootstrapValidation.js"></script>
    <script src="js/contact_me.js"></script>

    <!-- Theme JavaScript -->
    <script src="js/clean-blog.min.js"></script>

app/views/welcome/index.html.erb
<h1>Hola!, bienvenido a mi primera pagina en Rails</h1>
<%= link_to 'Mi Blog', controller: 'articles' %>